### ISSUE TITLE
Exception loading 'Glimpse.Core.Extensibility.ITab' of type 'Glimpse.AspNet.Tab.Cache'

### ISSUE THREAD

**Issue by jhanford** [Glimpse/Glimpse#1005]
I've done a basic install with a clean set of Glimpse web.config settings in ASP.NET MVC 4.5 and get this. Any ideas?

ERROR | Exception loading 'Glimpse.Core.Extensibility.ITab' of type 'Glimpse.AspNet.Tab.Cache'. | System.Reflection.TargetInvocationException--Exception has been thrown by the target of an invocation.--   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Glimpse.Core.Framework.ReflectionDiscoverableCollection`1.GetConcreteTypes(Assembly assembly, List`1 results)>>TypeInitializationException--The type initializer for 'Glimpse.AspNet.Tab.Cache' threw an exception.--Void .ctor()>>NullReferenceException--Object reference not set to an instance of an object.--Void .cctor()

**Comment by ajithasriram** [comment]
I have the same error as above. I have installed Glimpse.WebForms v1.1.1, Glimpse.AspNet v1.9.2 and Glimpse v1.8.6.
Is there anything we could do to set this right?

**Comment by eugen-vg** [comment]
It works for me with this fix https://github.com/Glimpse/Glimpse/pull/1002/commits/08548b994597b84829905df194b1d1128848cf6d
