### ISSUE TITLE
HUD not displaying data

### ISSUE THREAD

**Issue by GabrielMagurean** [Glimpse/Glimpse#1034]
Hi,

I am working on an ASP .NET Framework v4.6 MVC 5 app, I cannot get the Glimpse HUD to display any data... I get this:

####
No data has been found. This could be caused because:

- the data is still loading by the client, or
- no data has been received from the server (check to see if the data & metadata payloads are present), or
- no plugin has been loaded, or
- an error has been thrown in the client (please check your JavaScript console and let us know if anything is up).
####

I have installed from NuGet: Glimpse 1.8.6, Glimpse.ADO 1.7.3, Glimpse.AspNet 1.9.2, Glimpse.EF6 1.6.5, Glimpse.MVC5 1.5.3.

The erros I have in the logs are:
####
Exception loading 'Glimpse.Core.Extensibility.ITab' of type 'Glimpse.AspNet.Tab.Cache'. | System.Reflection.TargetInvocationException--Exception has been thrown by the target of an invocation.--   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at Glimpse.Core.Framework.ReflectionDiscoverableCollection`1.GetConcreteTypes(Assembly assembly, List`1 results)>>TypeInitializationException--The type initializer for 'Glimpse.AspNet.Tab.Cache' threw an exception.--Void .ctor()>>NullReferenceException--Object reference not set to an instance of an object.--Void .cctor()
####
and
####
2020-05-14 13:41:22.9789 | FATAL | AppDomain with Id: '18' and BaseDirectory: 'path to app here' has been unloaded. Any in memory data stores have been lost. Reason for shutdown: Change Notification for critical directories.;bin dir change or directory rename;HostingEnvironment initiated shutdown;Change Notification for critical directories.;bin dir change or directory rename;Change in C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\20b30f4c\6103a0c2\hash\hash.web;Change Notification for critical directories.;bin dir change or directory rename;Change Notification for critical directories.;bin dir change or directory rename;Change in C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\20b30f4c\6103a0c2\hash\hash.web;Change Notification for critical directories.;bin dir change or directory rename;Change Notification for critical directories.;bin dir change or directory rename;Change in C:\Windows\Microsoft.NET\Framework\v4.0.30319\Temporary ASP.NET Files\root\20b30f4c\6103a0c2\hash\hash.web;Change Notification for critical directories.;bin dir change or directory rename;Change Notification for critical directories.;bin dir change or directory rename;HostingEnvironment caused shutdown | 
####

What could I do ? I have read all the google pages about this :(

**Comment by GabrielMagurean** [comment]
![image](https://user-images.githubusercontent.com/65346181/81943406-03711680-9604-11ea-910f-b127c282e68f.png)
this is what I call the HUD, don't really know why.. I have seen it in one of many pages I have read while investigating

**Comment by GabrielMagurean** [comment]
I also have this in the Console:
"Failed to load resource: the server responded with a status of 404 () Glimpse.axd:1"
