### ISSUE TITLE
Glimpse.EF.AlternateType.GlimpseDbProviderServices' not found

### ISSUE THREAD

**Issue by leniel** [Glimpse/Glimpse#474]
Hey guys,

Just installed ```Glimpse EF6 1.3.1``` on my ASP.NET MVC 5 project. I have ```EntityFramework 6.0.0-beta1``` installed and after starting debugging I get this exception on the call to ```Membership.GetUser``` bellow:

```
if (user != null && user.Identity.IsAuthenticated)
{
    var membershipUser = Membership.GetUser(user.Identity.Name, true);
```

An exception of type 'System.MissingMethodException' occurred in mscorlib.dll but was not handled in user code

Additional information: Constructor on type 'Glimpse.EF.AlternateType.GlimpseDbProviderServices' not found.

StackTrace:

```
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Glimpse.Ado.AlternateType.GlimpseDbProviderFactory`1.GetService(Type serviceType)
   at System.Data.Common.DbProviderServices.GetProviderServices(DbProviderFactory factory)
   at System.Data.Common.DbProviderServices.GetProviderServices(DbConnection connection)
   at System.Web.Providers.ModelHelper.GetStorageMetadata(String providerName, DbConnection connection, String ssdl)
   at System.Web.Providers.ModelHelper.CreateMetadataWorkspace(String providerName, DbConnection connection, String csdl, String ssdl, String msl)
   at System.Web.Providers.ModelHelper.CreateEntityConnection(ConnectionStringSettings setting, String csdl, String ssdl, String msl)
   at System.Web.Providers.ModelHelper.CreateMembershipEntities(ConnectionStringSettings setting)
   at System.Web.Providers.DefaultMembershipProvider.GetUser(String username, Boolean userIsOnline)
   at System.Web.Security.Membership.GetUser(String username, Boolean userIsOnline)
   at Company.Client.Portal.Filters.GlobalPermissionAttribute.OnAuthorization(AuthorizationContext filterContext) in c:\Projects\Company.Client\Company.Client.Portal\Filters\GlobalPermissionAttribute.cs:line 67
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthorizationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<BeginInvokeAction>b__16(AsyncCallback asyncCallback, Object asyncState)
```

These are Glimpse packages I have installed on the project:

```
  <package id="Glimpse" version="1.5.0" targetFramework="net45" />
  <package id="Glimpse.Ado" version="1.4.1" targetFramework="net45" />
  <package id="Glimpse.AspNet" version="1.3.1" targetFramework="net45" />
  <package id="Glimpse.EF6" version="1.3.1" targetFramework="net45" />
  <package id="Glimpse.Mvc4" version="1.3.2" targetFramework="net45" />
```

I had to uninstall ```Glimpse EF6 1.3.1``` so that I could debug the project but I'd love to get this working on this project.

What's the problem?

<hr>

Not sure, but maybe this pull request will fix this: https://github.com/Glimpse/Glimpse/pull/470

**Comment by iprida** [comment]
I have this error:
```
An exception of type 'System.MissingMethodException' occurred in System.Data.Entity.dll but was not handled in user code
...
Constructor on type 'Glimpse.EF.AlternateType.GlimpseDbProviderServices' not found.
...
```
when in project with:
```
<package id="EntityFramework" version="6.1.3" targetFramework="net45" />
<package id="Glimpse" version="1.8.6" targetFramework="net45" />
  <package id="Glimpse.Ado" version="1.7.3" targetFramework="net45" />
  <package id="Glimpse.AspNet" version="1.9.2" targetFramework="net45" />
  <package id="Glimpse.EF6" version="1.6.5" targetFramework="net45" />
  <package id="Glimpse.Mvc5" version="1.5.3" targetFramework="net45" />
```
was added a reference to a library built on .NET 3.5 that use:
```
Framework\v3.5\System.Data.Entity.dll
```

The exception is thrown in .NET 3.5 lib at this line:
```
context.Events.Where(e => e.Type == type).FirstOrDefault();
```

I hope this will help to debug this issue.

**Comment by DavideYang125** [comment]
I have the same problem. Is it solved?

**Comment by DavideYang125** [comment]
I think the problem is related to ObjectContext.There is no problem with DbContext

**Comment by DavideYang125** [comment]
I solved  the problem by using Glimpse.EF43 and Glimpse.mvc3 instead of Glimpse.mvc5 and Glimpse.EF6.
Thanks
