### ISSUE TITLE
Allow users to disable use of Logical Call Context

### ISSUE THREAD

**Issue by TomDeWitt** [Glimpse/Glimpse#632]
I updated Glimpse ADO, ASP.NET, Core, EF5, and Mvc4 via NuGet this morning and I am now getting a run time error of Type 'System.Web.HttpContextWrapper' in assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable. 

The complete exception detail:

System.Runtime.Serialization.SerializationException was unhandled
  HResult=-2146233076
  Message=Type 'System.Web.HttpContextWrapper' in assembly 'System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.
  Source=WebDev.WebHost40
  StackTrace:
       at Microsoft.VisualStudio.WebHost.Host.ProcessRequest(Connection conn)
       at Microsoft.VisualStudio.WebHost.Server.OnSocketAccept(Object acceptedSocket)
       at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
       at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
  InnerException: 

I am running an MVC4 application from VS2010. The only changes to the project where the NuGet packages for Glimpse.

**Comment by jtkech** [comment]
@davidfowl just having the same issue while contributing on another project (Orchard cms). This when using the CallContext Logical Data to carry workcontext data among thread switching (e.g when async code), and when using this through a command shell that uses cross domain call...

You gave me the solution, as you said it just works with ObjectHandle, many thanks.

Best
