### ISSUE TITLE
Glimpse.Ado occasionally throws a SqlException

### ISSUE THREAD

**Issue by togakangaroo** [Glimpse/Glimpse#820]
Occasionally I get an error from Glimpse with the following stack trace

```
System.Data.SqlClient.SqlException was unhandled by user code
  HResult=-2146232060
  Message=Invalid column name 'CreatedOn'.
  Source=.Net SqlClient Data Provider
  ErrorCode=-2146232060
  Class=16
  LineNumber=2
  Number=207
  Procedure=""
  Server=(LocalDB)\v11.0
  State=1
  StackTrace:
       at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
       at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
       at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
       at System.Data.SqlClient.SqlDataReader.get_MetaData()
       at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
       at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
       at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
       at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
       at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
       at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
       at Glimpse.Ado.AlternateType.GlimpseDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
       at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
       at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c__DisplayClassb.<Reader>b__8()
       at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TInterceptionContext,TResult](Func`1 operation, TInterceptionContext interceptionContext, Action`1 executing, Action`1 executed)
  InnerException: 
```

It doesn't happen all the time but somewhat reliably when running with the VS debugger attached.

The only thing that I can think is that my entities have a CreatedOn DateTime column that is filled via `VisoftInc.EFHooks 2.0.0.0`

```
    public class MyAppDbContext : HookedDbContext
    {
        ...
        void registerHooks() {
            this.RegisterHook(new FillCreatedTimestamp());
            this.RegisterHook(new FillUpdatedTimestamp());
        }

        public MyAppDbContext() : base() { registerHooks(); }

        public MyAppDbContext(string connectionString) : base(connectionString) { registerHooks(); }
    }

    public class FillCreatedTimestamp : PreInsertHook<UserModifiable.Properties>
    {
        public override void Hook(UserModifiable.Properties entity, HookEntityMetadata metadata) {
            entity.LastModifiedBy = entity.CreatedBy ?? HttpContext.Current.IfNotNull(x => x.User).IfNotNull(x => x.Identity.Name);
            entity.LastModifiedOn = DateTime.UtcNow;
            entity.CreatedOn = entity.LastModifiedOn;
            entity.CreatedBy = entity.LastModifiedBy;
        }
    }
    public class FillUpdatedTimestamp : PreUpdateHook<UserModifiable.Properties>
    {
        public override void Hook(UserModifiable.Properties entity, HookEntityMetadata metadata) {
            entity.LastModifiedBy = HttpContext.Current.IfNotNull(x => x.User).IfNotNull(x => x.Identity.Name);
            entity.LastModifiedOn = DateTime.UtcNow;
        }
    }
```

This filters for only entities that match a certain type so I'm pretty confused about how that could be an issue.

**Comment by avanderhoorn** [comment]
@togakangaroo Is this something that is still and issue?

**Comment by migig** [comment]
@avanderhoorn Yes same problem exists [with MiniProfiler](https://github.com/MiniProfiler/dotnet/issues/56).

**Comment by avanderhoorn** [comment]
If its the same as what is happening with MiniProfiler then this is by design.
