### ISSUE TITLE
Glimpse.EF6 does not work with Npgsql.EntityFramework

### ISSUE THREAD

**Issue by cremor** [Glimpse/Glimpse#857]
I'm getting the following exception when I try to start my web application with both Glimpse.EF6 and Npgsql.EntityFramework referenced:

```
Unable to cast object of type 'Npgsql.NpgsqlConnection' to type 'Glimpse.Ado.AlternateType.GlimpseDbConnection'.
```

Full exception detail:

```
System.Data.Entity.Core.ProviderIncompatibleException was unhandled by user code
HResult=-2146233087
Message=An error occurred accessing the database. This usually means that the connection to the database failed. Check that the connection string is correct and that the appropriate DbContext constructor is being used to specify it or find it in the application's config file. See http://go.microsoft.com/fwlink/?LinkId=386386 for information on DbContext and connections. See the inner exception for details of the failure.
Source=EntityFramework
StackTrace:
     at System.Data.Entity.Utilities.DbProviderServicesExtensions.GetProviderManifestTokenChecked(DbProviderServices providerServices, DbConnection connection)
     at System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.<>c__DisplayClass1.<ResolveManifestToken>b__0(Tuple`3 k)
     at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
     at System.Data.Entity.Infrastructure.DefaultManifestTokenResolver.ResolveManifestToken(DbConnection connection)
     at System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInfo(DbConnection connection, DbProviderManifest& providerManifest)
     at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
     at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
     at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
     at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
     at System.Data.Entity.Internal.InternalContext.Initialize()
     at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
     at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
     at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
     at System.Data.Entity.Infrastructure.DbQuery`1.System.Collections.Generic.IEnumerable<TResult>.GetEnumerator()
     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at MyNamespace.MyController.Index()
     at lambda_method(Closure , ControllerBase , Object[] )
     at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
     at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
     at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
     at System.Web.Mvc.Async.AsyncControllerActionInvoker.ActionInvocation.InvokeSynchronousActionMethod()
     at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
     at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
     at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
     at System.Web.Mvc.Async.AsyncResultWrapper.End[TResult](IAsyncResult asyncResult, Object tag)
     at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
     at Castle.Proxies.AsyncControllerActionInvokerProxy.EndInvokeActionMethod_callback(IAsyncResult asyncResult)
     at Castle.Proxies.Invocations.AsyncControllerActionInvoker_EndInvokeActionMethod.InvokeMethodOnTarget()
     at Castle.DynamicProxy.AbstractInvocation.Proceed()
     at Glimpse.Core.Extensibility.CastleInvocationToAlternateMethodContextAdapter.Proceed()
     at Glimpse.Mvc.AlternateType.AsyncActionInvoker.EndInvokeActionMethod.NewImplementation(IAlternateMethodContext context)
     at Glimpse.Core.Extensibility.AlternateTypeToCastleInterceptorAdapter.Intercept(IInvocation invocation)
     at Castle.DynamicProxy.AbstractInvocation.Proceed()
     at Castle.Proxies.AsyncControllerActionInvokerProxy.EndInvokeActionMethod(IAsyncResult asyncResult)
     at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
     at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
InnerException: System.Data.Entity.Core.ProviderIncompatibleException
     HResult=-2146233087
     Message=The provider did not return a ProviderManifestToken string.
     Source=EntityFramework
     StackTrace:
          at System.Data.Entity.Core.Common.DbProviderServices.GetProviderManifestToken(DbConnection connection)
          at System.Data.Entity.Utilities.DbProviderServicesExtensions.GetProviderManifestTokenChecked(DbProviderServices providerServices, DbConnection connection)
     InnerException: System.InvalidCastException
          HResult=-2147467262
          Message=Unable to cast object of type 'Npgsql.NpgsqlConnection' to type 'Glimpse.Ado.AlternateType.GlimpseDbConnection'.
          Source=Glimpse.EF6
          StackTrace:
               at Glimpse.EF.AlternateType.GlimpseDbProviderServices.GetDbProviderManifestToken(DbConnection connection)
               at System.Data.Entity.Core.Common.DbProviderServices.GetProviderManifestToken(DbConnection connection)
          InnerException: 
```

Everything works fine if either Glimpse.EF6 is uninstalled or the default (SQL Server) provider is used instead of Npgsql.

Application information:
ASP.NET MVC 5.2.2 on .NET 4.5.1 in Visual Studio 2013
EntityFramework 6.1.1
Npgsql 2.2.1
Npgsql.EntityFramework 2.2.1
Glimpse 1.8.6
Glimpse.AspNet 1.9.1
Glimpse.Mvc5 1.5.3
Glimpse.Ado 1.7.3
Glimpse.EF6 1.6.4

**Comment by avanderhoorn** [comment]
@cremor Great to hear! Are things still working well?
