### ISSUE TITLE
Glimpse conflicts with RazorEngine?

### ISSUE THREAD

**Issue by impworks** [Glimpse/Glimpse#896]
In my ASP.NET MVC app I have an async controller message that must send an email. The email is processed via RazorEngine. Looks pretty straightforward, but Glimpse seems to conflict with it for some reason.

My code:
```
public virtual async Task<ActionResult> SendEmail()
{
    var path = "~/Views/Email/MyTemplate.cshtml";
    using (var reader = new StreamReader(HostingEnvironment.MapPath(path)))
    {
  	    // fails here:
        var result = Engine.Razor.RunCompile(reader.ReadToEnd(), path, null, new { Id = 1 });
    }
    // ...
}
```

The exception message:
```
Some environments conflict with current Glimpse async support.
Please set Glimpse:DisableAsyncSupport = true in Web.config, or see https://github.com/Glimpse/Glimpse/issues/632 for more details.
```

The exception stacktrace:
```
at Glimpse.AspNet.AspNetFrameworkProvider.AntiSerializationWrapper`1.GetObjectData(SerializationInfo info, StreamingContext context)
at System.Runtime.Serialization.ObjectCloneHelper.GetObjectData(Object serObj, String& typeName, String& assemName, String[]& fieldNames, Object[]& fieldValues)

at System.AppDomain.InternalCreateInstanceFromWithNoSecurity(String assemblyName, String typeName)
at RazorEngine.Compilation.CrossAppDomainCleanUp..ctor(AppDomain toWatch, IPrinter printer)
at RazorEngine.Compilation.CrossAppDomainCleanUp.CreateInitial()
at System.Lazy`1.CreateValue()
at System.Lazy`1.LazyInitValue()
at RazorEngine.Compilation.CrossAppDomainCleanUp.RegisterCleanup(String item, Boolean throwOnDefault)
at RazorEngine.Templating.DefaultCachingProvider.CacheTemplate(ICompiledTemplate template, ITemplateKey templateKey)
at RazorEngine.Templating.RazorEngineService.CompileAndCacheInternal(ITemplateKey key, Type modelType)
at RazorEngine.Templating.RazorEngineService.GetCompiledTemplate(ITemplateKey key, Type modelType, Boolean compileOnCacheMiss)
at RazorEngine.Templating.RazorEngineService.RunCompile(ITemplateKey key, TextWriter writer, Type modelType, Object model, DynamicViewBag viewBag)
at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass4.<RunCompile>b__3(TextWriter writer)
at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
```

Any idea what is wrong?

**Comment by CGijbels** [comment]
@impworks Did you check if it works by setting the `Glimpse:DisableAsyncSupport = true` in your web.config? The reason why is explained in the issue mentioned in the exception.

**Comment by impworks** [comment]
Setting the flag did actually help with the issue! But we use `async/await` extensively across the application and I am worried about hidden consequences of this solution. What does the flag actually do?

**Comment by CGijbels** [comment]
@impworks the flag disables putting a reference to the current `HttpContext` in the logical call context. 

In your case I would look at this [workaround](https://github.com/Glimpse/Glimpse/issues/632#issuecomment-29020863) I proposed in the linked issue. I think that might work for you as well if you put it around your code?

**Comment by avanderhoorn** [comment]
As an aside, this is no longer an issue in v2...
