### ISSUE TITLE
Could not find any resources appropriate for the specified culture or the neutral culture

### ISSUE THREAD

**Issue by mstDe3** [Glimpse/Glimpse#905]
Hello Guys,
I try to install Glimpse for my MVC2 application. I installed the latest versions of Glimpse, Glimpse.AspNet, Glimpse.MVC2 . It works greatest for my localhost, and I tried to pull Glimpse to our test server. After deployment and tunes web.config I tried to open glimpse.axd page but faced with the following problem:

> 2015-05-28 14:00:00,489 [11:ERROR(Errors)] System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Glimpse.AspNet.Resources.resources" was correctly embedded or linked into assembly "Glimpse.AspNet" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Glimpse.AspNet.Resources.get_ProcessRequestMissingRuntime()
   at Glimpse.AspNet.HttpHandler.ProcessRequest(HttpContextBase context)
   at Glimpse.AspNet.HttpHandler.ProcessRequest(HttpContext context)

I googled this error message on the many sites but I haven't found nothing that help me. 
May be you can? Thanks.

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
