### ISSUE TITLE
InvalidOperationException in WebForms.ProcessData

### ISSUE THREAD

**Issue by flcdrg** [Glimpse/Glimpse#910]
2015-06-09 11:43:13.3396 | DEBUG | Finish merging in the viewState data to the ControlTree | 
2015-06-09 11:43:13.3396 | ERROR | Exception executing tab of type 'webforms'. | System.InvalidOperationException--Sequence contains no elements--   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Glimpse.WebForms.Display.WebForms.ProcessData(IEnumerable`1 webFormsMessages)
   at Glimpse.WebForms.Display.WebForms.GetData(ITabContext context)
   at Glimpse.Core.Framework.GlimpseRuntime.ExecuteDisplays()

**Comment by flcdrg** [comment]
One cause seems to be Ajax calls to an .asmx service
