### ISSUE TITLE
Issue with running background services (with NHibernate access) from ASP.NET

### ISSUE THREAD

**Issue by soledadtctvtn** [Glimpse/Glimpse#916]
I've got this log when the background service (registered from Global.asax with Autofac IoC)
NHibernate.Exceptions.GenericADOException: could not execute query
[SQL: SELECT xxxxx FROM yyy_table this_ ORDER BY zzz_co desc] ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Glimpse.AspNet.AspNetFrameworkProvider.get_HttpRequestStore()
   at Glimpse.Core.Framework.Factory.<>c__DisplayClass5.<InstantiateRuntimePolicyStrategy>b__4()
   at NHibernate.Glimpse.InternalLoggers.SqlInternalLogger.Debug(Object message)
   at NHibernate.AdoNet.Util.SqlStatementLogger.LogCommand(String message, IDbCommand command, FormatStyle style)
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd)
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session)
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies, IResultTransformer forcedResultTransformer)
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters, IResultTransformer forcedResultTransformer)
 
I'm using below features:

- Glimpse 1.8.6, Glimpse.AspNet 1.9.2, Glimpse.Autofac 0.2.4, Glimpse.Mvc4 1.5.3, NHibernate.Glimpse 3.3.3.40011
- ASP MVC4, NHibernate, Autofac
- Per request lifescope for web request
Problem occurs on background services that are initialized once from Global.asax

This issue was raised from https://github.com/csainty/Glimpse.RavenDb/issues/7

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
