### ISSUE TITLE
An item with the same key has already been added. Glimpse.EF6

### ISSUE THREAD

**Issue by btull89** [Glimpse/Glimpse#921]
My MVC5 app crashes if I have Glimpse.EF6 and Glimpse.Ado attached to Glimpse. The app only crashes on one of our test webservers. It doesn't have any issues locally or on our production server.
If I delete the EF6 and ADO Glimpse dlls on the test server, the app runs.

I am using EF 6.1.1.
The test server is Windows Server 2008R2 running IIS 7.5.
Our production server is Windows Server 2012R2 running IIS 8.5.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Glimpse.EF.AlternateType.InvariantNameResolver.get_RegisteredFactories()
   at Glimpse.EF.AlternateType.InvariantNameResolver.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.ResolverChain.<>c__DisplayClass3.<GetService>b__0(IDbDependencyResolver r)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Data.Entity.Infrastructure.DependencyResolution.ResolverChain.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.CompositeResolver`2.GetService(Type type, Object key)
   at System.Data.Entity.Infrastructure.DependencyResolution.DbDependencyResolverExtensions.GetService[T](IDbDependencyResolver resolver, Object key)
   at System.Data.Entity.Utilities.DbConnectionExtensions.GetProviderInvariantName(DbConnection connection)
   at System.Data.Entity.Core.EntityClient.EntityConnection.get_ConnectionString()
   at System.Data.Entity.Core.Objects.ObjectContext..ctor(EntityConnection connection, Boolean isConnectionConstructor, ObjectQueryExecutionPlanFactory objectQueryExecutionPlanFactory, Translator translator, ColumnMapFactory columnMapFactory)
   at System.Data.Entity.Core.Objects.ObjectContext..ctor(EntityConnection connection)
   at System.Data.Entity.Internal.MockingProxies.ObjectContextProxy.CreateNew(EntityConnectionProxy entityConnection)
   at System.Data.Entity.Internal.ClonedObjectContext..ctor(ObjectContextProxy objectContext, DbConnection connection, String connectionString, Boolean transferLoadedAssemblies)
   at System.Data.Entity.Internal.InternalContext.UseTempObjectContext()
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.Include(String path)
   at System.Data.Entity.Infrastructure.DbQuery`1.Include(String path)
   at MyProject.Data.Repositories.GenericRepository`1.<SelectCollectionAll>b__0(DbQuery`1 current, String entity)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at MyProject.Data.Repositories.GenericRepository`1.SelectCollectionAll(List`1 entityList)
   at MyProject.Data.Repositories.UserRepository.GetUserRole(String userName)
   at MyProject.Services.Services.UserService.GetUserRole(String userName)
   at MyProject.MVC.UserAuthorization.CustomRoleProvider.GetRolesForUser(String username)
   at System.Web.Security.RolePrincipal.GetRoles()
   at System.Web.Security.Roles.GetRolesForUser(String username)
   at System.Web.Security.Roles.GetRolesForUser()
   at MyProject.MVC.MvcApplication.CreateAndDecryptAuthTicket(Boolean corruptedAuthTicket)
   at MyProject.MVC.MvcApplication.Application_PostAuthenticateRequest()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.Web.Util.ArglessEventHandlerProxy.Callback(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226

**Comment by Cloetn** [comment]
For anyone having the same problem. The problem is that multiple versions of some DbFactory are installed. 

The error occurents when accessing the DbProviderFactoriesExecutionTask.Factories in

https://github.com/Glimpse/Glimpse/blob/master/source/Glimpse.EF/AlternateType/InvariantNameResolver.cs

The Factories are filled in on https://github.com/Glimpse/Glimpse/blob/master/source/Glimpse.Ado/Inspector/Core/DbProviderFactoriesExecutionTask.cs, multiple DbFactories are found with the same name. The current code to this date still has this problem.

**Comment by Cloetn** [comment]
We are currently having the same issue. For anyone who is interested or has the same problem. Check the InvariantNameResolver.RegisteredFactories, it returns the original  DbProviderFactoriesExecutionTask.Factories dictionary but then reversed. So the value is suddenly the key. I don't know if it's meant to be like that or not. But because these things are reversed we had this issue because 2 DbFactories had different keys but the same value. 

![glimpseproblems](https://cloud.githubusercontent.com/assets/449344/20562238/e4f0bf26-b182-11e6-914c-99547e2dd23e.png)
