### ISSUE TITLE
"Stack Empty" exception during UpdateModelBinding

### ISSUE THREAD

**Issue by piersh** [Glimpse/Glimpse#936]
my Glimpse.log (v1.8.6 (core)) contains a whole bunch of these:

````
2015-11-10 12:38:31.5755 | ERROR | Exception calling subscriber with message of type 'Glimpse.Mvc.AlternateType.ValueProvider`1+GetValue+Message[System.Web.Mvc.IEnumerableValueProvider]'. | System.InvalidOperationException--Stack empty.--   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Stack`1.Pop()
   at Glimpse.Mvc.Tab.ModelBinding.GetModel(Stack`1 stack, String parameter)
   at Glimpse.Mvc.Tab.ModelBinding.UpdateModelBinding[T](Message message, ITabSetupContext context)
   at Glimpse.Mvc.Tab.ModelBinding.<>c__DisplayClassd.<Setup>b__b(Message message)
   at Glimpse.Core.Extensibility.Subscriber`1.Execute(Object message)
   at Glimpse.Core.Extensibility.MessageBroker.Publish[T](T message)
````

no idea why...

**Comment by avanderhoorn** [comment]
Unfortunately there isn't much I can do at the moment. That said, the progress is being tracked at #226
