### ISSUE TITLE
Can not instantiate proxy of class: System.Web.Mvc.Async.AsyncControllerActionInvoker

### ISSUE THREAD

**Issue by get2ksh** [Glimpse/Glimpse#960]
I have installed the following Glimpse packages, 

Glimpse.Core, Glimpse.Aspnet, Glimpse.MVC5.

When enabling glimpse on my application which is of MVC front end and WebAPI integration, On a subsequent MVC request to IIS, I am getting an error "Can not instantiate proxy of class: System.Web.Mvc.Async.AsyncControllerActionInvoker. Could not find a parameterless constructor.". After disabling Glimpse my application works fine. 

I have tried uninstalling the packages and reinstalling them again, reinstall it with lower version of glimpse and tried few config changes, but nothing as helped me to resolve the issue. One clue that i can make is the MVC project is using MVC5. Require urgent help to work this issue around to get the glimpse running. 

The stack trace is as below.

<Exception><Type>Castle.DynamicProxy.InvalidProxyConstructorArgumentsException</Type><Message>Can not instantiate proxy of class: System.Web.Mvc.Async.AsyncControllerActionInvoker.
Could not find a parameterless constructor.</Message><Source>Glimpse.Core</Source><StackTrace>   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyInstance(Type proxyType, List`1 proxyArguments, Type classToProxy, Object[] constructorArguments)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyWithTarget(Type classToProxy, Type[] additionalInterfacesToProxy, Object target, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Castle.DynamicProxy.ProxyGenerator.CreateClassProxyWithTarget(Type classToProxy, Object target, ProxyGenerationOptions options, Object[] constructorArguments, IInterceptor[] interceptors)
   at Glimpse.Core.Framework.CastleDynamicProxyFactory.WrapClass[T](T instance, IEnumerable`1 methodImplementations, IEnumerable`1 mixins, IEnumerable`1 constructorArguments)
   at Glimpse.Core.Framework.CastleDynamicProxyFactory.WrapClass[T](T instance, IEnumerable`1 methodImplementations, IEnumerable`1 mixins)
   at Glimpse.Mvc.AlternateType.AsyncActionInvoker.TryCreate(IAsyncActionInvoker originalObj, IAsyncActionInvoker&amp; newObj, IEnumerable`1 mixins, Object[] constructorArgs)
   at Glimpse.Core.Extensibility.AlternateType`1.TryCreate(T originalObj, T&amp; newObj)
   at Glimpse.Mvc.AlternateType.ControllerFactory.CreateController.ProxyActionInvoker(IController iController)
   at Glimpse.Mvc.AlternateType.ControllerFactory.CreateController.PostImplementation(IAlternateMethodContext context, TimerResult timerResult)
   at Glimpse.Core.Extensibility.AlternateMethod.NewImplementation(IAlternateMethodContext context)
   at Glimpse.Core.Extensibility.AlternateTypeToCastleInterceptorAdapter.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IControllerFactoryProxy_1.CreateController(RequestContext requestContext, String controllerName)
   at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController&amp; controller, IControllerFactory&amp; factory)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously)</StackTrace></Exception>

**Comment by MikeMattox** [comment]
I am having the same problem.  Did you happen to find a resolution to the issue?

**Comment by avanderhoorn** [comment]
Currently we don't support WebAPI, looking to do more in the future though.
