### ISSUE TITLE
AccessViolationException when Suppress JIT optimization is checked

### ISSUE THREAD

**Issue by erwindevreugd** [Glimpse/Glimpse#974]
I ran into an issue when in Visual Studio 2015 Community "Options>Debugging>General>Suppress JIT optimization on module load" is checked".

Glimps 2.0.0-beta1
MVC 6.0.0-rc1-final
DNX 4.5.1

   at Proxy_From_ViewResult_To_IViewResult_5.get_StatusCode()
   at Glimpse.Agent.Internal.Inspectors.WebDiagnosticsInspector.OnBeforeActionResult(IActionContext actionContext, Object result)
   at Proxy_Method_From_<>f__AnonymousType10`2_To_Void OnBeforeActionResult(Glimpse.Agent.Internal.Inspectors.Mvc.Proxies.IActionContext, System.Object)(Object , Object , IProxyFactory )
   at Microsoft.Extensions.DiagnosticAdapter.ProxyDiagnosticSourceMethodAdapter.<>c__DisplayClass1_0.<Adapt>b__0(Object listener, Object data)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.Write(String diagnosticName, Object parameters)
   at Microsoft.Extensions.DiagnosticAdapter.DiagnosticSourceAdapter.System.IObserver<System.Collections.Generic.KeyValuePair<System.String,System.Object>>.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.AspNet.Mvc.Diagnostics.FilterActionInvokerDiagnosticSourceExtensions.BeforeActionResult(DiagnosticSource diagnosticSource, ActionContext actionContext, IActionResult result)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultAsync>d__56.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultFilterAsync>d__55.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.InvokeResultFilterAsync()
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResultFilterAsync>d__55.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.InvokeResultFilterAsync()
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAllResultFiltersAsync>d__54.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.InvokeAllResultFiltersAsync(IActionResult result)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResourceFilterAsync>d__49.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.InvokeResourceFilterAsync()
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeResourceFilterAsync>d__49.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.InvokeResourceFilterAsync()
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.InvokeAllResourceFiltersAsync()
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.InvokeAsync()
   at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.InvokeActionAsync(RouteContext context, ActionDescriptor actionDescriptor)
   at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.RouteAsync(RouteContext context)
   at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.<RouteAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Mvc.Routing.InnerAttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNet.Mvc.Routing.AttributeRoute.RouteAsync(RouteContext context)
   at Microsoft.AspNet.Routing.RouteCollection.<RouteAsync>d__9.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Routing.RouteCollection.RouteAsync(RouteContext context)
   at Microsoft.AspNet.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNet.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNet.Builder.UseExtensions.<>c__DisplayClass0_1.<Use>b__2()
   at ASPNETTemplate.Startup.<>c.<Configure>b__3_0(HttpContext context, Func`1 next) in D:\Git\Repos\ASPNETTemplate\Startup.cs:line 62

After unchecking "Suppress JIT optimization on module load" and Glimpse works as expected

**Comment by avanderhoorn** [comment]
I'm assuming this is Glimpse v2 on Asp.Net core? If so it should be over at https://github.com/Glimpse/Glimpse.Client.Prototype
