### ISSUE TITLE
Issues when EF Code First needs to create a database

### ISSUE THREAD

**Issue by ac931274** [Glimpse/Glimpse#995]
We have a large project that I have added Glimpse to.  The project runs when Glimpse is not installed,  it runs when the database has previously been created.  We get the following error when EF needs to create the database on the server:
Unable to cast object of type 'System.Data.SqlClient.SqlConnection' to type 'Glimpse.Ado.AlternateType.GlimpseDbConnection'.

The stack trace is:
   at Glimpse.EF.AlternateType.GlimpseDbProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   at System.Data.Entity.Core.Objects.ObjectContext.CreateDatabase()
   at System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection)
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   at System.Data.Entity.Infrastructure.DbQuery`1.System.Collections.IEnumerable.GetEnumerator()
   at System.Data.Entity.QueryableExtensions.Load(IQueryable source)
.......

The versions of the Glimpse packages in use are :
  <package id="Glimpse" version="1.8.6" targetFramework="net452" />
  <package id="Glimpse.Ado" version="1.7.3" targetFramework="net452" />
  <package id="Glimpse.AspNet" version="1.9.2" targetFramework="net452" />
  <package id="Glimpse.EF6" version="1.6.5" targetFramework="net452" />
  <package id="Glimpse.Mvc5" version="1.5.3" targetFramework="net452" />

If I remove the reference to Glimpse.EF6 and Glimpse.ADO the project runs again and creates the database on demand as before.  Am I missing something?

Jonathan

**Comment by ac931274** [comment]
Sorry packages are:
package id="Glimpse" version="1.8.6" targetFramework="net452"
package id="Glimpse.Ado" version="1.7.3" targetFramework="net452"
package id="Glimpse.AspNet" version="1.9.2" targetFramework="net452"
package id="Glimpse.EF6" version="1.6.5" targetFramework="net452" 
package id="Glimpse.Mvc5" version="1.5.3" targetFramework="net452"
